# Generated by Django 4.1.4 on 2022-12-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('plot_number', models.CharField(max_length=255)),
                ('land_reference', models.CharField(max_length=255)),
                ('county', models.CharField(choices=[('Lamu', 'Lamu'), ('Meru', 'Meru'), ('Embu', 'Embu'), ('Kisii', 'Kisii'), ('Bomet', 'Bomet'), ('Narok', 'Narok'), ('Nyeri', 'Nyeri'), ('Kitui', 'Kitui'), ('Kwale', 'Kwale'), ('Wajir', 'Wajir'), ('Nandi', 'Nandi'), ('Busia', 'Busia'), ('Siaya', 'Siaya'), ('Kiambu', 'Kiambu'), ('Isiolo', 'Isiolo'), ('Kilifi', 'Kilifi'), ('Nakuru', 'Nakuru'), ('Vihiga', 'Vihiga'), ('Kisumu', 'Kisumu'), ('Migori', 'Migori'), ('Nairobi', 'Nairobi'), ('Nyamira', 'Nyamira'), ('Baringo', 'Baringo'), ('Samburu', 'Samburu'), ('Turkana', 'Turkana'), ('Garissa', 'Garissa'), ('Mombasa', 'Mombasa'), ('Mandera', 'Mandera'), ('Makueni', 'Makueni'), ('Kajiado', 'Kajiado'), ('Kericho', 'Kericho'), ('Bungoma', 'Bungoma'), ('Homa Bay', 'Homa Bay'), ('Kakamega', 'Kakamega'), ('Laikipia', 'Laikipia'), ('Marsabit', 'Marsabit'), ('Machakos', 'Machakos'), ('Murang’a', 'Murang’a'), ('Kirinyaga', 'Kirinyaga'), ('Nyandarua', 'Nyandarua'), ('Tana River', 'Tana River'), ('West Pokot', 'West Pokot'), ('Trans-Nzoia', 'Trans-Nzoia'), ('Uasin Gishu', 'Uasin Gishu'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Taita Taveta', 'Taita Mak Taveta'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet')], max_length=255)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
